//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Blackchess_prefab
    {
        public const string BundleName = "blackchess_prefab";
        public const string BLACKCHESS = "blackchess";
    }
    public class Blackwin_jpg
    {
        public const string BundleName = "blackwin_jpg";
        public const string BLACKWIN = "blackwin";
    }
    public class Uigameover_prefab
    {
        public const string BundleName = "uigameover_prefab";
        public const string UIGAMEOVER = "uigameover";
    }
    public class Uihomepanel_prefab
    {
        public const string BundleName = "uihomepanel_prefab";
        public const string UIHOMEPANEL = "uihomepanel";
    }
    public class Whitechess_prefab
    {
        public const string BundleName = "whitechess_prefab";
        public const string WHITECHESS = "whitechess";
    }
    public class Whitewin_jpg
    {
        public const string BundleName = "whitewin_jpg";
        public const string WHITEWIN = "whitewin";
    }
}
